"""
src/export_engine.py
Downloadable brand kit packaging.

Produces a ZIP containing:
  - SVG + PNG logo concepts
  - Slogan list (TXT + JSON)
  - Colour palette sheet (PNG + JSON)
  - Font recommendation sheet (TXT)
  - Social captions (TXT per platform)
  - Multilingual copy (TXT)
  - Campaign prediction summary (TXT)
  - Brand consistency report (Markdown)
  - Animated GIF (if available)
"""

from __future__ import annotations
import io
import json
import logging
import zipfile
from datetime import datetime
from typing import Optional

log = logging.getLogger(__name__)


# ─────────────────────────────────────────────────────────────────────────────
# Palette PNG
# ─────────────────────────────────────────────────────────────────────────────

def _palette_png(swatches: list[dict]) -> bytes:
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        from matplotlib.patches import Rectangle

        n = len(swatches)
        fig, axes = plt.subplots(1, n, figsize=(n*2.5, 3))
        fig.patch.set_facecolor("#0A0A08")
        if n == 1: axes = [axes]
        for ax, sw in zip(axes, swatches):
            ax.add_patch(Rectangle((0,0),1,1, color=sw["hex"]))
            ax.set_xlim(0,1); ax.set_ylim(0,1.25)
            ax.axis("off")
            ax.text(0.5, 1.12, sw["role"].upper(), ha="center", va="bottom",
                    fontsize=7, color="#F5F2EB",
                    fontfamily="monospace", fontweight="normal")
            ax.text(0.5,-0.06, sw["hex"].upper(),  ha="center", va="top",
                    fontsize=8, color="#C8A94A", fontfamily="monospace")
            ax.text(0.5,-0.18, sw["name"],          ha="center", va="top",
                    fontsize=6.5, color="#6A6A64", fontfamily="monospace")
        plt.tight_layout(pad=0.3)
        buf = io.BytesIO()
        plt.savefig(buf, format="png", dpi=150, bbox_inches="tight",
                    facecolor="#0A0A08")
        plt.close(fig)
        buf.seek(0)
        return buf.read()
    except Exception as e:
        log.warning("Palette PNG failed: %s", e)
        return b""


# ─────────────────────────────────────────────────────────────────────────────
# Consistency report
# ─────────────────────────────────────────────────────────────────────────────

def _brand_report_md(
    company:       str,
    industry:      str,
    tone:          str,
    score_overall: float,
    score_grade:   str,
    breakdown:     dict,
    strengths:     list[str],
    improvements:  list[str],
    slogans:       list[str],
    palette:       list[dict],
    font:          dict,
    campaign:      dict,
) -> str:
    now = datetime.utcnow().strftime("%B %d, %Y")
    lines = [
        f"# {company} — Brand Consistency Report",
        f"*Generated by NovaTech AI · {now}*",
        "",
        "---",
        "",
        "## Brand Identity Summary",
        f"| Attribute | Value |",
        f"|-----------|-------|",
        f"| Company   | {company} |",
        f"| Industry  | {industry} |",
        f"| Tone      | {tone} |",
        "",
        "---",
        "",
        f"## Brand Consistency Score: {score_overall}/100 ({score_grade})",
        "",
        "### Breakdown",
    ]
    for k,v in breakdown.items():
        lines.append(f"- **{k}**: {v}/100")
    lines += ["", "### ✓ Strengths"]
    for s in strengths:
        lines.append(f"- {s}")
    lines += ["", "### → Improvements"]
    for imp in improvements:
        lines.append(f"- {imp}")
    lines += [
        "",
        "---",
        "",
        "## Slogans",
    ]
    for i, sl in enumerate(slogans, 1):
        lines.append(f"{i}. {sl}")
    lines += [
        "",
        "---",
        "",
        "## Colour Palette",
        "| Role | Hex | Name | Meaning |",
        "|------|-----|------|---------|",
    ]
    for sw in palette:
        lines.append(f"| {sw.get('role','')} | `{sw.get('hex','')}` | {sw.get('name','')} | {sw.get('meaning','')} |")
    lines += [
        "",
        "---",
        "",
        "## Typography",
        f"- **Heading**: {font.get('heading','')}",
        f"- **Body**: {font.get('body','')}",
        f"- **Accent**: {font.get('accent','')}",
        f"- **Rationale**: {font.get('rationale','')}",
        "",
        "---",
        "",
        "## Campaign Prediction",
    ]
    if campaign:
        lines += [
            f"- **Predicted ROI**: {campaign.get('roi','—')}×",
            f"- **Engagement Score**: {campaign.get('engagement_score','—')}/10",
            f"- **CTR**: {campaign.get('ctr','—')}",
            f"- **Source**: {campaign.get('source','—')} ({campaign.get('confidence','—')} confidence)",
        ]
    lines += [
        "",
        "---",
        "",
        "*NovaTech AI · CRS AI Capstone 2025–26 · Scenario 1*",
    ]
    return "\n".join(lines)


# ─────────────────────────────────────────────────────────────────────────────
# Public API
# ─────────────────────────────────────────────────────────────────────────────

def build_brand_kit_zip(
    company:        str,
    industry:       str,
    tone:           str,
    slogans:        list[str],
    palette:        list[dict],
    font:           dict,
    logo_svgs:      list[dict],       # [{"name":..,"svg":..}]
    captions:       list[dict],       # [{"platform":..,"caption":..,"hashtags":..,"cta":..}]
    translations:   list[dict],       # [{"language":..,"text":..}]
    campaign:       dict,
    score_overall:  float,
    score_grade:    str,
    breakdown:      dict,
    strengths:      list[str],
    improvements:   list[str],
    animation_gif:  Optional[bytes] = None,
) -> bytes:
    """
    Package all brand assets into a ZIP and return as bytes.
    """
    buf = io.BytesIO()
    slug = company.lower().replace(" ","_")

    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:

        # ── README
        zf.writestr(f"{slug}_brand_kit/README.txt",
            f"NovaTech AI — Brand Kit for {company}\n"
            f"Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}\n\n"
            "Contents:\n"
            "  logos/          SVG logo concepts\n"
            "  palette/        Colour palette (JSON + PNG)\n"
            "  typography/     Font recommendations (TXT)\n"
            "  slogans/        Taglines (TXT + JSON)\n"
            "  social/         Platform captions (TXT per platform)\n"
            "  multilingual/   Translated copy (TXT)\n"
            "  campaign/       Prediction summary (TXT)\n"
            "  report/         Brand consistency report (Markdown)\n"
            "  animation/      Branded GIF (if generated)\n"
        )

        # ── Logos (SVG)
        for lc in logo_svgs:
            name = lc["name"].lower().replace(" ","_")
            zf.writestr(f"{slug}_brand_kit/logos/{name}.svg", lc["svg"])

        # ── Palette JSON + PNG
        zf.writestr(
            f"{slug}_brand_kit/palette/palette.json",
            json.dumps(palette, indent=2),
        )
        png = _palette_png(palette)
        if png:
            zf.writestr(f"{slug}_brand_kit/palette/palette.png", png)

        # ── Typography
        font_txt = (
            f"Typography Recommendations for {company}\n"
            f"{'='*50}\n\n"
            f"Heading Font : {font.get('heading','')}\n"
            f"Body Font    : {font.get('body','')}\n"
            f"Accent Font  : {font.get('accent','')}\n"
            f"Style        : {font.get('style','')}\n\n"
            f"Rationale:\n{font.get('rationale','')}\n\n"
            f"Google Fonts links:\n"
            f"  Heading : https://fonts.google.com/specimen/{font.get('heading','').replace(' ','+')}\n"
            f"  Body    : https://fonts.google.com/specimen/{font.get('body','').replace(' ','+')}\n"
            f"  Accent  : https://fonts.google.com/specimen/{font.get('accent','').replace(' ','+')}\n"
        )
        zf.writestr(f"{slug}_brand_kit/typography/fonts.txt", font_txt)

        # ── Slogans
        slogans_txt = f"Brand Slogans & Taglines — {company}\n\n" + \
                      "\n".join(f"{i+1}. {s}" for i,s in enumerate(slogans))
        zf.writestr(f"{slug}_brand_kit/slogans/slogans.txt",  slogans_txt)
        zf.writestr(f"{slug}_brand_kit/slogans/slogans.json", json.dumps(slogans, indent=2))

        # ── Social captions
        for cap in captions:
            plat    = cap.get("platform","unknown").replace(" ","_").replace("/","_")
            content = (
                f"Platform : {cap.get('platform','')}\n"
                f"{'='*50}\n\n"
                f"Caption:\n{cap.get('caption','')}\n\n"
                f"Hashtags:\n{' '.join(cap.get('hashtags',[]))}\n\n"
                f"CTA:\n{cap.get('cta','')}\n\n"
                f"Strategy Note:\n{cap.get('strategy','')}\n"
            )
            zf.writestr(f"{slug}_brand_kit/social/{plat}.txt", content)

        # ── Multilingual
        if translations:
            ml_lines = [f"Multilingual Copy — {company}\n{'='*50}\n"]
            for t in translations:
                ml_lines.append(f"\n[{t.get('language','')}] (source: {t.get('source','')})")
                ml_lines.append(t.get("text",""))
            zf.writestr(f"{slug}_brand_kit/multilingual/translations.txt", "\n".join(ml_lines))

        # ── Campaign summary
        if campaign:
            camp_txt = (
                f"Campaign Performance Prediction — {company}\n{'='*50}\n\n"
                f"Predicted ROI          : {campaign.get('roi','—')}×\n"
                f"Engagement Score       : {campaign.get('engagement_score','—')}/10\n"
                f"Click-Through Rate     : {campaign.get('ctr','—')}\n"
                f"Conversion Rate        : {campaign.get('conversion_rate','—')}\n"
                f"Prediction Source      : {campaign.get('source','—')}\n"
                f"Confidence             : {campaign.get('confidence','—')}\n\n"
                f"Recommendations:\n"
            )
            for r in campaign.get("recommendations",[]):
                camp_txt += f"  · {r}\n"
            zf.writestr(f"{slug}_brand_kit/campaign/prediction.txt", camp_txt)

        # ── Brand consistency report (Markdown)
        report_md = _brand_report_md(
            company, industry, tone, score_overall, score_grade,
            breakdown, strengths, improvements, slogans, palette, font, campaign)
        zf.writestr(f"{slug}_brand_kit/report/brand_consistency_report.md", report_md)

        # ── Animation GIF
        if animation_gif:
            zf.writestr(f"{slug}_brand_kit/animation/{slug}_brand.gif", animation_gif)

    buf.seek(0)
    return buf.read()
